[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/valmiioworkspace/shared_invite/zt-1vijp4a9v-4yIzpuBpW5_ukxLLzSZD5w"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"


